### ISSUE TITLE
Suggestion for requirements.txt for training

### ISSUE THREAD

**Issue by rubas** [ufal/low-resource-gec-wnut2019#2]
This package combination seems to be compatible with your forked version of `tensor2tensor==1.12.0`.

```
mesh-tensorflow==0.0.5
tensorboard==1.13.1
tensorflow==1.13.2
tensorflow-estimator==1.13.0
tensorflow-gan==1.0.0.dev0
tensorflow-hub==0.7.0
tensorflow-metadata==0.21.0
tensorflow-probability==0.5.0
```

**Comment by arahusky** [comment]
Hello, thank you for your suggestion, but I think that adding our updated Tensor2Tensor library as the only requirement is sufficient as the rest packages are downloaded automatically when installing it.

To make it more clear, I added new requirements.txt into training directory and updated its README, which now contains information to simply run ```pip install -r requirements.txt```
